version: "3.8"
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./config:/app/config
      - ./data:/app/data
      - ./domain.yml:/app/domain.yml
    depends_on:
      - action_server

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
